import logging
import random
from io import StringIO
from pathlib import Path
from typing import Dict, List, Optional

import dargs
from ase.data import atomic_masses, chemical_symbols, atomic_numbers
from ase.io import read, write
from dargs import Argument

from pfd.constants import lmp_conf_name, lmp_input_name, lmp_traj_name
from .conf_sampling_task_group import ConfSamplingTaskGroup
from .lmp_template_task_group import (
    DUMP_ID,
    MODEL_PLACEHOLDER,
    LmpTemplateTaskGroup,
)
from .task import ExplorationTask


def make_lmp_input_param(
    conf_file: str,
    ens: str,
    nsteps: int,
    dt: float,
    trj_freq: int,
    temp: float,
    tau_t: float,
    press: Optional[float] = None,
    tau_p: float = 0.5,
    seed: Optional[int] = None,
    no_pbc: bool = False,
    type_map: Optional[List[str]] = None,
) -> str:
    """Generate a LAMMPS input script from MD parameters.

    Units follow the ASE-stage convention: ``dt``, ``tau_t`` and ``tau_p``
    are in **fs** and converted to LAMMPS-metal ps internally; ``press`` is
    in **bar** (LAMMPS metal pressure unit). The generated script satisfies
    the pfd template contract (pfd_model.pt2 placeholder, read_data conf,
    pfd_traj dump with forces).
    """
    if "npt" in ens and press is None:
        raise ValueError("press must be provided for npt ensemble")
    if "npt" in ens and no_pbc:
        raise ValueError(f"ensemble {ens} conflicts with no_pbc")
    valid = ("nvt", "nve", "npt", "npt-i", "npt-iso", "npt-a", "npt-aniso", "npt-t", "npt-tri")
    if ens not in valid:
        raise ValueError(f"unknown ensemble '{ens}'; supported: {valid}")

    if type_map is None:
        raise ValueError("type_map (element order) is required")
    elements = list(type_map)
    masses = [float(atomic_masses[atomic_numbers[e]]) for e in elements]
    pair_coeff_elems = " ".join(elements)

    seed_val = seed if seed is not None else random.randrange(1, 1000000)

    # fs -> ps (LAMMPS metal time unit)
    dt_ps = dt * 1e-3
    tau_t_ps = tau_t * 1e-3
    tau_p_ps = tau_p * 1e-3

    L = []
    L.append("# generated by pfd parameterized LAMMPS exploration")
    L.append("units           metal")
    L.append("dimension       3")
    L.append("boundary        %s" % ("f f f" if no_pbc else "p p p"))
    L.append("atom_style      atomic")
    L.append("atom_modify     map yes")
    L.append("")
    L.append("read_data       %s" % conf_file)
    L.append("")
    for jj, m in enumerate(masses):
        L.append("mass            %d %f" % (jj + 1, m))
    L.append("")
    L.append("pair_style      deepmd %s" % MODEL_PLACEHOLDER)
    L.append("pair_coeff      * * %s" % pair_coeff_elems)
    L.append("")
    L.append("neighbor        2.0 bin")
    L.append("neigh_modify    every 1 delay 0 check yes")
    L.append("")
    L.append("thermo_style    custom step time temp pe ke etotal press vol density")
    L.append("thermo          %d" % trj_freq)
    L.append("thermo_modify   flush yes")
    L.append("")
    L.append(
        "dump            %s all custom %d %s id type element x y z fx fy fz"
        % (DUMP_ID, trj_freq, lmp_traj_name)
    )
    L.append("dump_modify     %s element %s" % (DUMP_ID, pair_coeff_elems))
    L.append("dump_modify     %s sort id" % DUMP_ID)
    L.append("")
    L.append("velocity        all create %f %d mom yes rot yes dist gaussian" % (temp, seed_val))
    L.append("")
    if ens in ("npt", "npt-i", "npt-iso"):
        L.append(
            "fix             pfd_npt all npt temp %f %f %f iso %f %f %f"
            % (temp, temp, tau_t_ps, press, press, tau_p_ps)
        )
    elif ens in ("npt-a", "npt-aniso"):
        L.append(
            "fix             pfd_npt all npt temp %f %f %f aniso %f %f %f"
            % (temp, temp, tau_t_ps, press, press, tau_p_ps)
        )
    elif ens in ("npt-t", "npt-tri"):
        L.append(
            "fix             pfd_npt all npt temp %f %f %f tri %f %f %f"
            % (temp, temp, tau_t_ps, press, press, tau_p_ps)
        )
    elif ens == "nvt":
        L.append("fix             pfd_nvt all nvt temp %f %f %f" % (temp, temp, tau_t_ps))
    elif ens == "nve":
        L.append("fix             pfd_nve all nve")
    if no_pbc:
        L.append("velocity        all zero linear")
        L.append("fix             pfd_mom all momentum 1 linear 1 1 1")
    L.append("")
    L.append("timestep        %f" % dt_ps)
    L.append("run             %d" % nsteps)
    L.append("")
    return "\n".join(L)


class LmpParamTaskGroup(ConfSamplingTaskGroup):
    """Parameterized LAMMPS exploration task group (ASE-style config).

    Generates the LAMMPS input script from MD parameters instead of a
    user-written template. Selected when a stage dict has no
    ``input_lmp_template`` key. Units match the ASE stage convention
    (dt/tau_t/tau_p in fs, press in bar, temps in K).
    """

    def __init__(self):
        super().__init__()
        self.md_set = False

    def set_md(
        self,
        temps: List[float],
        press: Optional[List[float]] = None,
        ens: str = "npt",
        dt: float = 1.0,
        nsteps: int = 1000,
        trj_freq: int = 100,
        tau_t: float = 100.0,
        tau_p: float = 500.0,
        seed: Optional[int] = None,
        no_pbc: bool = False,
        type_map: Optional[List[str]] = None,
    ) -> None:
        self.temps = temps
        self.press = press if press is not None else [None]
        self.ens = ens
        self.dt = dt
        self.nsteps = nsteps
        self.trj_freq = trj_freq
        self.tau_t = tau_t
        self.tau_p = tau_p
        self.seed = seed
        self.no_pbc = no_pbc
        self.type_map = type_map
        self.md_set = True

    def make_task(self) -> "LmpParamTaskGroup":
        import itertools

        if not self.conf_set:
            raise RuntimeError("confs are not set")
        if not self.md_set:
            raise RuntimeError("MD settings are not set")
        self.clear()
        confs = self._sample_confs()
        for cc, tt, pp in itertools.product(confs, self.temps, self.press):
            self.add_task(self._make_lmp_task(cc, tt, pp))
        return self

    def _make_lmp_task(self, conf_str: str, tt: float, pp: Optional[float]) -> ExplorationTask:
        atoms = read(StringIO(conf_str), format="extxyz")
        specorder = self.type_map
        if specorder is None:
            symbols = atoms.get_chemical_symbols()
            specorder = sorted(set(symbols), key=lambda s: symbols.index(s))
        buf = StringIO()
        write(
            buf, atoms, format="lammps-data", units="metal",
            atom_style="atomic", masses=True, specorder=specorder,
        )
        script = make_lmp_input_param(
            conf_file=lmp_conf_name,
            ens=self.ens,
            nsteps=self.nsteps,
            dt=self.dt,
            trj_freq=self.trj_freq,
            temp=tt,
            tau_t=self.tau_t,
            press=pp,
            tau_p=self.tau_p,
            seed=self.seed,
            no_pbc=self.no_pbc,
            type_map=specorder,
        )
        task = ExplorationTask()
        task.add_file(lmp_input_name, script).add_file(lmp_conf_name, buf.getvalue())
        return task

    @classmethod
    def args(cls) -> List[dargs.Argument]:
        doc_temps = "List of temperatures in K for MD simulation."
        doc_press = "List of pressures in bar for MD simulation (optional)."
        doc_ens = "Ensemble: nvt, nve, npt (iso), npt-aniso, npt-tri."
        doc_dt = "MD time step in fs."
        doc_nsteps = "Number of MD steps."
        doc_trj_freq = "Trajectory dump frequency in MD steps."
        doc_tau_t = "Temperature coupling time in fs."
        doc_tau_p = "Pressure coupling time in fs."
        doc_seed = "Random seed for velocity initialization (optional)."
        doc_no_pbc = "Disable periodic boundary conditions."
        doc_type_map = (
            "Element order for the LAMMPS data file and pair_coeff; defaults "
            "to the element order of the sampled configurations."
        )
        return [
            Argument("temps", list, optional=False, doc=doc_temps),
            Argument("press", [list, type(None)], optional=True, default=None, doc=doc_press),
            Argument("ens", str, optional=True, default="npt", doc=doc_ens),
            Argument("dt", float, optional=True, default=1.0, doc=doc_dt),
            Argument("nsteps", int, optional=True, default=1000, doc=doc_nsteps),
            Argument("trj_freq", int, optional=True, default=100, doc=doc_trj_freq),
            Argument("tau_t", float, optional=True, default=100.0, doc=doc_tau_t),
            Argument("tau_p", float, optional=True, default=500.0, doc=doc_tau_p),
            Argument("seed", [int, type(None)], optional=True, default=None, doc=doc_seed),
            Argument("no_pbc", bool, optional=True, default=False, doc=doc_no_pbc),
            Argument("type_map", [list, type(None)], optional=True, default=None, doc=doc_type_map),
        ]

    @classmethod
    def normalize_config(cls, data: Dict, strict: bool = True) -> Dict:
        ta = cls.args()
        base = Argument("base", dict, ta)
        data = base.normalize_value(data, trim_pattern="_*")
        base.check_value(data, strict=strict)
        return data

    @classmethod
    def make_task_grp_from_conf(
        cls, task_grp_config: Dict, init_confs: List[str], *args, **kwargs
    ) -> "List[LmpParamTaskGroup]":
        confs_idx = task_grp_config.pop("conf_idx")
        n_sample = task_grp_config.pop("n_sample")
        task_grp_ls = []
        for ii in confs_idx:
            atoms_ls = read(init_confs[ii], index=":")
            if not isinstance(atoms_ls, list):
                atoms_ls = [atoms_ls]
            atoms_ls_str = []
            for atoms in atoms_ls:
                buf = StringIO()
                write(buf, atoms, format="extxyz")
                atoms_ls_str.append(buf.getvalue())
            task_grp = cls()
            task_grp.set_conf(
                conf_list=atoms_ls_str, n_sample=n_sample, random_sample=True
            )
            config = cls.normalize_config(task_grp_config, strict=False)
            task_grp.set_md(**config)
            task_grp_ls.append(task_grp)
        return task_grp_ls
